version: '3.7'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
     - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app_dev
  kafka-1:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    command: >
          sh -c "kafka-topics.sh --create --topic test-events --zookeeper zookeeper:2181 --partitions 2 --replication-factor 1"
    networks:
      - app_dev
    volumes:
      - './kafka1_data:/bitnami/kafka'
    depends_on:
      - zookeeper
  kafka-2:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app_dev
    volumes:
      - './kafka2_data:/bitnami/kafka'
    depends_on:
      - zookeeper

# volumes:
#   kafka1_data:
#     driver: local   
#   kafka2_data:
#     driver: local
    
networks:
  app_dev:
    external: false
    name: app_dev
